### ISSUE TITLE
.ReaderException: Table definition not found for table 可能是什么原因

### ISSUE THREAD

**Issue by kevinbin** [alibaba/innodb-java-reader#41]
ibd 是 mysql 8.0

[ERROR] 2022-08-22 13:17:07,777 [main]  reader.cli.InnodbReaderBootstrap        (InnodbReaderBootstrap.java:397)        -Error occurred: Table definition not found for table tb_ec_system_user
com.alibaba.innodb.java.reader.exception.ReaderException: Table definition not found for table tb_ec_system_user
        at com.alibaba.innodb.java.reader.TableReaderFactory.createTableReader(TableReaderFactory.java:97)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.createTableReader(InnodbReaderBootstrap.java:689)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.queryAll(InnodbReaderBootstrap.java:412)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.run(InnodbReaderBootstrap.java:322)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.main(InnodbReaderBootstrap.java:129)
JVM does not support unmapping memory-mapped files.

**Comment by thinh9e** [comment]
I have the same issue as you when I run on Win 10. I switched to Linux with MySQL installed, it can work for me.

**Comment by elpaca** [comment]
破案了，windows上将路径中的 \ 换成 / 就可以了，可能获取表名的时候直接用/ split了

```
(base) PS D:\opt\bin> java -jar .\innodb-java-reader-cli.jar -i "D:\opt\mysql-5.7.44-winx64\data\sky_take_out\dish.ibd" -create-table-sql-file-path .\sky.sql -c show-all-pages
[ERROR] 2025-11-19 22:02:57,142 [main]  reader.cli.InnodbReaderBootstrap        (InnodbReaderBootstrap.java:397)       -Error occurred: Table definition not found for table D:\opt\mysql-5.7.44-winx64\data\sky_take_out\dish
com.alibaba.innodb.java.reader.exception.ReaderException: Table definition not found for table D:\opt\mysql-5.7.44-winx64\data\sky_take_out\dish
        at com.alibaba.innodb.java.reader.TableReaderFactory.createTableReader(TableReaderFactory.java:97)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.createTableReader(InnodbReaderBootstrap.java:689)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.showAllPages(InnodbReaderBootstrap.java:573)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.run(InnodbReaderBootstrap.java:314)
        at com.alibaba.innodb.java.reader.cli.InnodbReaderBootstrap.main(InnodbReaderBootstrap.java:129)
(base) PS D:\opt\bin> java -jar .\innodb-java-reader-cli.jar -i "D:/opt/mysql-5.7.44-winx64/data/sky_take_out/dish.ibd" -create-table-sql-file-path .\sky.sql -c show-all-pages
=====page number, page type, other info=====
0,FILE_SPACE_HEADER,space=65,numPagesUsed=6,size=8,xdes.size=1
1,IBUF_BITMAP
2,INODE,inode.size=6
3,INDEX,root.page=true,index.id=79,level=0,numOfRecs=23,num.dir.slot=6,garbage.space=0
4,INDEX,root.page=true,index.id=80,level=0,numOfRecs=23,num.dir.slot=6,garbage.space=0
5,INDEX,root.page=true,index.id=94,level=0,numOfRecs=23,num.dir.slot=6,garbage.space=0
6,INDEX,root.page=true,index.id=94,level=0,numOfRecs=23,num.dir.slot=6,garbage.space=0
7,ALLOCATED
(base) PS D:\opt\bin>
```
